theme: jekyll-theme-minimal
title: Yanyan Yuan (è¢ç‚ç‚)
description: PhD student at School of Aeronautics and Astronautics, Zhejiang University 
             Robotics & Robotic Arm & Humanoid Robot & RL

social_links:
  - name: "ğŸ“§ Email"
    url: mailto:your.email@example.com
  - name: "ğŸ± GitHub"
    url: https://github.com/yourusername
  - name: "ğŸ§  çŸ¥ä¹"
    url: https://www.zhihu.com/people/yourzhihuusername

