theme: jekyll-theme-minimal
title: Yanyan Yuan (è¢ç‚ç‚)
description: PhD student at School of Aeronautics and Astronautics, Zhejiang Universityï¼›Robotics & Robotic Arm & Humanoid Robot & RL

social_links:
  - name: "ğŸ“§ Email"
    url: mailto:your.email@example.com
  - name: "ğŸ± GitHub"
    url: https://github.com/yourusername
  - name: "ğŸ§  çŸ¥ä¹"
    url: https://www.zhihu.com/people/yourzhihuusername

author:
  name: "Yanyan Yuan"
  bio: "çƒ­çˆ±æŠ€æœ¯çš„å¼€å‘è€…"
  location: "Hangzhou, China"
  email: "yuanyan_hy@zju.edu.cn"
  links:
    - label: "ğŸ“§ Email"
      url: "mailto:yuanyan_hy@zju.edu.cn"
    - label: "ğŸ™ GitHub"
      url: "https://github.com/Stylite-Y"
    - label: "ğŸ“ çŸ¥ä¹"
      url: "https://www.zhihu.com/people/yuan-yan-yan-47"

sidebar:
  # nav: "å¿«é€Ÿé“¾æ¥"
  author:
    name: true
    avatar: true
    bio: true
    location: true
    links: true
